# Generated by Django 4.0.5 on 2022-06-14 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobOpen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=200)),
                ('region', models.CharField(max_length=200)),
                ('position', models.CharField(max_length=500)),
                ('compensation', models.IntegerField()),
                ('description', models.TextField()),
                ('skills', models.CharField(max_length=200)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company', to='Company.companys')),
            ],
        ),
    ]
