# Generated by Django 4.0.5 on 2022-06-17 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
    ]
